config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#welcome'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_in',  :to => 'devise/sessions#new',     :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  scope :u do
    get '/:id',                      to: 'users#show',         as: 'user'
    get '/:id/queue',                to: 'song_queues#latest', as: 'latest_queue'
    get '/:id/queue/:song_queue_id', to: 'song_queues#show',   as: 'song_queue'
  end
  
  scope :queue do
    post   '/',    to: 'song_queues#create',  as: 'create_queue'
    delete '/:id', to: 'song_queues#destroy', as: 'destroy_queue'
  end

  resources :song_requests, only: [:show, :create]
  resources :configs
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  devise :omniauthable, omniauth_providers: %i[twitch]

  validates_presence_of :name

  has_many :song_queues
  has_one :config

  after_create :create_config

  def self.from_omniauth(auth)
    if @user = find_by(name: auth.info.nickname, uid: nil)
      @user.update_attributes(uid: auth.uid, provider: auth.provider)
      return @user
    elsif @user = find_by(name: auth.info.nickname, uid: auth.uid, provider: auth.provider)
      @user
    else
      create(name: auth.info.nickname, uid: auth.uid, provider: auth.provider)
    end
  end

  private

  def create_config
    Config.create(user: self)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
#require 'pry'
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitch
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: "Twitch") if is_navigational_format?
    else
      session["devise.twitch_data"] = request.env["omniauth.auth"]
      redirect_to root_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.friendly.find(params[:id])
    authorize @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.haml
%h1 
  This is a page of 
  = @user.name
  It will contain stats of this user
  
  - if current_user && @user == current_user
    %p 
      Your config:
      = form_for @user.config do |f|
        = f.label :region, "Region", title: "two letter ISO 3166-1 alpha-2 country code"
        = f.select :region, IsoCountryCodes::Code.all.map(&:alpha2)

        = f.label :length_min, "Minimum song length"
        = f.number_field :length_min
        
        = f.label :length_max, "Maximum song length"
        = f.number_field :length_max

        = f.submit "Update"
    = form_tag create_queue_path, method: :post, id: 'going_live_button' do
      = button_tag type: 'submit', class: 'btn', data: { disable_with: "Opening..." } do
        Open new queue
  User has following queues: 
  - @user.song_queues.each do |q|
    = link_to song_queue_path(song_queue_id: q.id) do
      = q.created_at
    = q.finished_at