config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#welcome'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_in',  :to => 'devise/sessions#new',     :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  scope :u do
    get '/:id',                      to: 'users#show',         as: 'user'
    get '/:id/queue',                to: 'song_queues#latest', as: 'latest_queue'
    get '/:id/queue/:song_queue_id', to: 'song_queues#show',   as: 'song_queue'
  end
  
  scope :queue do
    post   '/',    to: 'song_queues#create',  as: 'create_queue'
    delete '/:id', to: 'song_queues#destroy', as: 'destroy_queue'
  end

  resources :song_requests, only: [:show, :create]
  resources :configs
end

app/models/song_queue.rb
class SongQueue < ApplicationRecord
  belongs_to :owner, class_name: :User, foreign_key: :user_id
  has_many :song_requests

  scope :unfinished, -> { where(finished_at: nil) }
end

app/controllers/song_queues_controller.rb
class SongQueuesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :latest]

  def show
    @owner = User.friendly.find(params[:id])
    @song_queue = @owner.song_queues.includes(song_requests: [:user, :song])
      .find(params[:song_queue_id])
    authorize @song_queue
  end
  
  def latest
    @owner = User.friendly.find(params[:id])
    @song_queue = @owner.song_queues.includes(song_requests: [:user, :song]).last
    authorize @song_queue || SongQueue
  end

  def create
    if current_user.song_queues.unfinished.any?
      flash.now[:danger] = 'You have an unfinished queue. Finish your old queue to create a new one.'
      authorize SongQueue
    else
      @song_queue = current_user.song_queues.build
      authorize @song_queue
      @song_queue.save
    end
    redirect_to latest_queue_path(current_user)
  end

  def destroy
    @song_queue = SongQueue.find(params[:id])
    authorize @song_queue
    if @song_queue.destroy
      flash[:success] = 'Queue successfully deleted'
    end
    redirect_back fallback_location: root_url
  end
end

app/helpers/song_queues_helper.rb
module SongQueuesHelper
end

app/views/song_queues/_song_queue.html.haml
= form_with url: destroy_queue_path(song_queue), local: true, method: :delete do |f|
  = f.submit 'Destroy', class: 'btn' 

app/views/song_queues/latest.html.haml
- if @song_queue
  This is song_queue#show
  - if current_user 
    = form_with url: song_requests_path do |f|
      = f.text_field :request, placeholder: "Request a song...", required: true
      = f.hidden_field :song_queue, value: @song_queue.id
      .input-group-append
        = f.submit "Request", class: 'btn'
  this queue with id
  = @song_queue.id
  has 
  = @song_queue.song_requests.count
  requests:
  %table
    = render @song_queue.song_requests
- else
  Shit's not real yo

app/views/song_queues/show.html.haml
This is song_queue#show
- if current_user 
  = form_with url: song_requests_path do |f|
    = f.text_field :request, placeholder: "Request a song...", required: true
    = f.hidden_field :song_queue, value: @song_queue.id
    .input-group-append
      = f.submit "Request", class: 'btn'
this queue with id
= @song_queue.id
has 
= @song_queue.song_requests.count
requests:
%table
  = render @song_queue.song_requests